---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.10
    cpu: 2
    memory: 2G
  configure_script:
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - bazel test -k
      --build_tag_filters=-haskell
      --test_tag_filters=-haskell
      --remote_download_minimal
      --config=ci
      --config=release
      //c-toxcore/...
